version: '3.8'

services:
  db:
    container_name: test-postgres-db
    build:
      context: .
      dockerfile: Dockerfile-pg
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    cap_add:
      - NET_ADMIN
      - NET_RAW
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 30s
      retries: 3
  pgbouncer:
    container_name: test-postgres-pgbouncer
    image: edoburu/pgbouncer:latest
    environment:
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_NAME: test_db
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "6432:5432"
  web:
    container_name: test-postgres-web
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    restart: always

volumes:
  postgres-data:

networks:
  web:
    driver: host
